### ISSUE TITLE
Chat download

### ISSUE THREAD

**Issue by churrodude666** [siuramka/KickDownloader#1]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Write your feature request here

Hey, I wondered since the vods do now have a chat replay, will you be adding the option to download them too? Would be awesome

Thanks

**Comment by siuramka** [comment]
I'll take a look, thanks for the update!

**Comment by siuramka** [comment]
I'll take a look, thanks for the update!

**Comment by siuramka** [comment]
The API to retrieve messages is done by current timestamp and it only has a ?start_time property. It appear that ever 5 seconds it makes a API call to get messages from that 5 second period, meaning you would need to make 12 API calls to retrieve a 1 minute worth of messages, 120 calls for 10 minutes worth etc. It also could be somewhat optimized probably, but it would still require lots of API calls. 

Thus, not going to add this feature unless something new pops up.

Now on Twitch, you have GQL access and only need to make a few requests.
