### ISSUE TITLE
Bulk download

### ISSUE THREAD

**Issue by s0902rx** [siuramka/KickDownloader#2]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

When trying to download vods in bulk i get this error:

![KickDownloaderWPF_6snRFZlcZl](https://github.com/siuramka/KickDownloader/assets/79232286/dd8c12eb-fde2-48f7-8ce7-77fe4ef682d5)

Also searching vods and clips doesn't work.

**Comment by siuramka** [comment]
Hey, as you can read in the description. You can see the working features, searching isn't one of them.

Now downloading multiple clips/vods should work. If that's the issue you're experiencing, can you give the list of the vods you're trying to download in bulk as I wasn't able to replicate your issue.

**Comment by s0902rx** [comment]
It happens with any vod i tried, i can do Vod download ---> Enqueue Download but the url list thing does not work. 

Also i'm on windows 11 if that matters.

**Comment by siuramka** [comment]
Please submit a video. Couldn't replicate on w11 either.

**Comment by siuramka** [comment]
Also, did you try to reinstall the program ? And did it work before ?

**Comment by s0902rx** [comment]
I don't know if it's installed it's just an executable in a folder i think, it never worked. I downloaded it from here: 
https://github.com/siuramka/KickDownloaderSharp/releases/tag/alpha-0.1


https://github.com/siuramka/KickDownloader/assets/79232286/7fd53817-8c1b-4677-81ba-a35375b5b818

**Comment by s0902rx** [comment]
I deleted and redownloaded the folder too.

**Comment by siuramka** [comment]
Follow the build instruction on https://github.com/siuramka/KickDownloader 
You downloaded some old release. You need to build the executable yourself.

**Comment by siuramka** [comment]
You downloaded an old release, you're supposed to download the source code and build it yourself as people were hesitant to download the .exe before :D I added a new release that is current and works. Thanks for the update and the video!
