### ISSUE TITLE
Unable to get info

### ISSUE THREAD

**Issue by Ratzzyyy** [siuramka/KickDownloader#3]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Windows GUI Application

### Describe your issue here

Getting an error since today, worked fine up until now.

This is the error log:
ERROR: Sequence contains no elements
![Screenshot (476)](https://github.com/siuramka/KickDownloader/assets/80396790/c5b55e84-93c9-4276-a3ca-464cc515c3fd)
![Screenshot (477)](https://github.com/siuramka/KickDownloader/assets/80396790/284e7a9f-48e1-4472-bb98-c97184b83907)

**Comment by LeonRoyal** [comment]
same issue for me

**Comment by LeonRoyal** [comment]
Use the kick downloader from the chrome extension store for now

**Comment by othergun** [comment]
Hi all, same for me...

**Comment by siuramka** [comment]
Will look into it.

**Comment by LeonRoyal** [comment]
> Will look into it.

🙌👍

**Comment by siuramka** [comment]
Kick upped their Cloudflare game, so my chromium API client get blocked. I will look into ways of solving this.

**Comment by caydex6** [comment]
Any news?

**Comment by JIREXv1** [comment]
> Kick upped their Cloudflare game, so my chromium API client get blocked. I will look into ways of solving this.

Ain't no way you cant literally just start using yt-dlp. I've started using yt-dlp since the downloading issue and it's worked perfectly fine. Just gotta provide the m3u8 https://kicktools.net/kick-vod-m3u8

**Comment by Bramhutls** [comment]
> Ain't no way you cant literally just start using yt-dlp. I've started using yt-dlp since the downloading issue and it's worked perfectly fine. Just gotta provide the m3u8 https://kicktools.net/kick-vod-m3u8

Can you choose to download between set timestamps with yt-dlp? Very easy with this one.
