### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by sirvannes** [siuramka/KickDownloader#4]
### Checklist

- [X] I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
- [X] I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))

### Edition

Unsure

### Describe your issue here

Kick Downloader is now broken due to Kick updating their vod system, now its unable to fetch info. 

https://cdn.discordapp.com/attachments/1015661299641884803/1187431351943708722/image.png?ex=6596dc9f&is=6584679f&hm=cb149bb710e4efa381d61e10e010008e296fbcaeaa8c225a7e17f83975e85bf9&

**Comment by othergun** [comment]
> ### Checklist
> * [x]  I have checked the [issue page](https://github.com/lay295/TwitchDownloader/issues?q=is%3Aissue) for duplicates
> * [x]  I am running the latest version ([download here](https://github.com/lay295/TwitchDownloader/releases/latest))
> 
> ### Edition
> Unsure
> 
> ### Describe your issue here
> Kick Downloader is now broken due to Kick updating their vod system, now its unable to fetch info.
> 
> https://cdn.discordapp.com/attachments/1015661299641884803/1187431351943708722/image.png?ex=6596dc9f&is=6584679f&hm=cb149bb710e4efa381d61e10e010008e296fbcaeaa8c225a7e17f83975e85bf9&
> 
> ### Add any related files or extra information here
> _No response_

https://github.com/siuramka/KickDownloader/issues/3#issuecomment-1859138559

**Comment by othergun** [comment]
Answer : https://github.com/siuramka/KickDownloader/issues/3#issuecomment-1859138559

**Comment by LeonRoyal** [comment]
😭😭
